export const weatherData = [
  {
    cityName: "London",
    temperature: 19,
    date: "2023-06-12",
    humidity: 76,
    chanceOfRain: 20,
    wind: 12,
    weatherCondition: "cloudy",
    tomorrowTemp: 21,
  },
  {
    cityName: "New York",
    temperature: 25,
    date: "2023-06-12",
    humidity: 55,
    chanceOfRain: 10,
    wind: 8,
    weatherCondition: "sunny",
    tomorrowTemp: 26,
  },
  {
    cityName: "Sydney",
    temperature: 15,
    date: "2023-06-12",
    humidity: 63,
    chanceOfRain: 15,
    wind: 11,
    weatherCondition: "partly cloudy",
    tomorrowTemp: 16,
  },
  {
    cityName: "Tokyo",
    temperature: 28,
    date: "2023-06-12",
    humidity: 70,
    chanceOfRain: 25,
    wind: 10,
    weatherCondition: "sunny",
    tomorrowTemp: 30,
  },
];
